### ISSUE TITLE
Dialog Extended  Breaks Modal

### ISSUE THREAD

**Issue by davetoolin** [jasonday/jQuery-UI-Dialog-extended#12]
Love the responsive feature but 
I have a dialog box on a page with modal set to true. When I add this to my page the box is no longer modal.  Eg. I can click on the background and the dialog will close. 
Dave

**Comment by jasonday** [comment]
Set the option clickOut to false in your init.

**Comment by ioliva** [comment]
I agree with @jasonday. The dialog being modal only means (according to the specification) that it renders an overlay over the rest of page elements, so that the user cannot interact with anything else until he/she has closed the dialog or taken any action on it.

That being said, "clickOut" just provides an alternative, configurable method of closing the dialog, besides clicking the close button.
